### ISSUE TITLE
Multiplex

### ISSUE THREAD

**Issue by okdistribute** [local-first-web/relay#3]
Looking at the code, I can't tell -- does each document create it's own websocket connection? Is there any interest in a feature that multiplexes document events over a single websocket connection to the relay? 

The benefits are improved performance when a user has many documents open, especially on mobile devices.

**Comment by HerbCaudill** [comment]
There's one websocket connection per discovery key (per peer). 

The discovery key should be a globally unique ID -- in practice probably a UUID, but could be anything. What it _represents_ can be anything you want: 

- In lf/state we used it to represent a "repo" containing many documents. 
- In lf/auth we use the team ID as the discovery key. 
- I could also imagine scenarios where it'd make sense for it to be a document ID. 

At any rate it's definitely not locked into representing a single document, so technically yeah it's a multiplex connection on some level.
